## 1. Pandas stands for Python Data Analysis Library
## 2. Pandas has two collections: Series and DataFrame
## 3. pandas can: load data, manipulate data, prepare data, model and analyze data.
## 4. to permanently sort a DataFrame, we use the inplace=True keyword
## 5. CSV stands for comma separated values
## 6. When cleaning data, we don't use null values.

In [44]:
7. # Import NumPy, use one of the NumPy methods and create an array with a sha7pe of (2, 3, 2). You can use the reshape method -- `.reshape()`

import numpy as np
np.arange(12).reshape(2,3,2)

#8 Use NumPy `.linspace()` to crUeate a with 6 linearly spaced values between 0 and 20
array = np.linspace(0,20,6)
print(array)

#9. Make a Deep Copy of the above array
array_copy = array.copy()

#10 Concatenate these 3 arrays into a new array named 'newArray'
array1 = np.array([[25, 16]])
array2 = np.array([[11, 2], [13, 4]])
array3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((array1, array2, array3))

#11. Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray)

#12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.
newArray = np.concatenate((array1, array2, array3))
sortedArray = np.sort(newArray)

row1, row2, row3, row4, row5, row6 = sortedArray
print("Row 1:", row1)
print("Row 2:", row2)
print("Row 3:", row3)
print("Row 4:", row4)
print("Row 5:", row5)
print("Row 6:", row6)

#13. Combined and sort the following arrays into one called 'comboArray'
one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three))
sortedComboArray = np.sort(comboArray)

print(sortedComboArray)

#14. Take 'comboArray' and perform the following slicing activities:
sec1 = sortedComboArray[1]
sec2 = sortedComboArray[2:]
sec3 = sortedComboArray[1:5]
sec4 = sortedComboArray[-6:]
sec5 = sortedComboArray[:16]
sec6 = sortedComboArray[20::2]
sec7 = sortedComboArray[-1::-5]

print("sec1:", sec1)
print("sec2:", sec2)
print("sec3:", sec3)
print("sec4:", sec4)
print("sec5:", sec5)
print("sec6:", sec6)
print("sec7:", sec7)

#15 Using `Series`, create a `DataFrame`
import pandas as pd

data = {
    'Ingredients': ['Flour', 'Milk', 'Eggs', 'Spam'],
    'Quantity': [4, 1, 2, 1],
    'Unit': ['Cups', 'Cup', 'large', 'can']
}

df = pd.DataFrame(data)
print(df)

#16. Take this data and create a DataFrame named studentData

data = {
    'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
    'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
    'Age': [21, 23, 24, 21],
    'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
    'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
}

studentData = pd.DataFrame(data)
print(studentData)

#17. Add a new column to the DataFrame with the following deserts:

studentData = pd.DataFrame(data)

desserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData['Desserts'] = desserts

print(studentData)

[ 0.  4.  8. 12. 16. 20.]
Row 1: [16 25]
Row 2: [ 2 11]
Row 3: [ 4 13]
Row 4: [ 7 81]
Row 5: [5 6]
Row 6: [11 12]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec1: 1
sec2: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
sec3: [1 2 3 4]
sec4: [22 23 24 25 26 27]
sec5: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17]
sec6: [24 26]
sec7: [27 22 15 10  3]
  Ingredients  Quantity   Unit
0       Flour         4   Cups
1        Milk         1    Cup
2        Eggs         2  large
3        Spam         1    can
      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket
      Name  Height Qualification  address  Age        Pets           sport  \
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

       Desserts
0     ice cream
1  Cashew Fudge
2       waffels
3  Carrot Halwa